demo/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

js_info_dict = {
    'packages': ('temporale','demo','demo.biography',),
}

urlpatterns = patterns('',
    # Examples:
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='demo-index'),
    url(r'^temporale/', include('temporale.urls')),
    url(r'^notes/', include('adhesive.urls')),
    url(r'^bio/', include('demo.biography.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
)

# serve static content in debug mode
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            'show_indexes' : True
        }),
        url(r'^(?P<path>favicon.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    )

temporale/urls.py
from django.conf.urls import url
from temporale import views
from temporale.vcal import events_as_vcal

urlpatterns = [
    url(r'^(?:calendar/)?$',
        views.today_view,
        name='temporale-today'),

    url(r'^(?P<year>\d{4})/$',
        views.year_view,
        name='temporale-yearly-view'),

    url(r'^(\d{4})/(0?[1-9]|1[012])/$',
        views.month_view,
        name='temporale-monthly-view'),

    url(r'^(\d{4})/(0?[1-9]|1[012])/([0-3]?\d)/$',
        views.day_view,
        name='temporale-daily-view'),

    url(r'^events/$',
        views.event_listing,
        name='temporale-events'),

    url(r'^events/new/$',
        views.add_event,
        name='temporale-add-event'),

    url(r'^events/add/$',
        views.add_event),

    url(r'^events/(\d+)/$',
        views.event_view,
        name='temporale-event'),

    url(r'^events/(\d+)/(\d+)/$',
        views.occurrence_view,
        name='temporale-occurrence'),

    url(r'^vcal/$',
        events_as_vcal,
        name='temporale-vcal'),
]

temporale/models.py
# -*- coding: utf-8 *-*
from __future__ import absolute_import
from __future__ import unicode_literals
from datetime import datetime, time
from django.utils import timezone
from django.utils.translation import ugettext as _
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.db import models
from django.db.models.signals import post_save
# from dorsale.managers import DorsaleSiteManager
# from adhesive.models import DorsaleAnnotatedBaseModel
from dorsale.tools import class_from_name
from dateutil import rrule

import logging
logger = logging.getLogger(__name__)

from .settings import BASE_CLASS, MANAGER

BASE_CLASS = class_from_name(BASE_CLASS)
MANAGER = class_from_name(MANAGER)

logger.info(BASE_CLASS)
logger.info(MANAGER)

__all__ = (
    'EventType',
    'Event',
    'Occurrence',
    'create_event'
)


class EventType(models.Model):
    """
    Simple ``Event`` classification.
    """
    code = models.SlugField(_('code'), max_length=15, unique=True, help_text=_('Abbreviation of the label (internal use)'))
    label = models.CharField(_('label'), max_length=50, help_text=_('Visible name of the event type'))
    content_type = models.ForeignKey(ContentType, verbose_name=_('content type'), blank=True, null=True, help_text=_('This event type is valid for related objects of this type'))

    class Meta:
        verbose_name = _('event type')
        verbose_name_plural = _('event types')

    def __unicode__(self):
        return self.label


class Event(BASE_CLASS):
    """
    Container model for general metadata and associated ``Occurrence`` entries.
    """
    title = models.CharField(_('title'), max_length=63, help_text=_('Name of the event'))
    description = models.CharField(_('description'), max_length=255, help_text=_('Short description of the event'))
    event_type = models.ForeignKey(EventType, verbose_name=_('event type'), null=True, help_text=_('Type of the event'))

    content_type = models.ForeignKey(ContentType, verbose_name=_('content type'), blank=True, null=True, help_text=_('Type of the related object'))
    object_id = models.IntegerField(_('object id'), blank=True, null=True, help_text=_('ID of the related object'))
    content_object = GenericForeignKey('content_type', 'object_id')

    class Meta:
        verbose_name = _('event')
        verbose_name_plural = _('events')
        ordering = ('title', )
        permissions = [
            ('view_event', _('Can view event')),
        ]

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('temporale-event', [str(self.id)])

    def _make_params(self, **kwargs):
        """
        Add dorsale attributes, if they exist
        """
        for p in ('createdby', 'site'):
            if hasattr(self, p):
                kwargs[p] = getattr(self, p)
        return kwargs

    def add_occurrences(self, start_time, end_time, **rrule_params):
        """
        Add one or more occurences to the event using a comparable API to
        ``dateutil.rrule``.

        If ``rrule_params`` does not contain a ``freq``, one will be defaulted
        to ``rrule.DAILY``.

        Because ``rrule.rrule`` returns an iterator that can essentially be
        unbounded, we need to slightly alter the expected behavior here in order
        to enforce a finite number of occurrence creation.

        If both ``count`` and ``until`` entries are missing from ``rrule_params``,
        only a single ``Occurrence`` instance will be created using the exact
        ``start_time`` and ``end_time`` values.
        """
        rrule_params.setdefault('freq', rrule.DAILY)

        params = self._make_params(start_time=start_time, end_time=end_time)
        if 'count' not in rrule_params and 'until' not in rrule_params:
            return self.occurrence_set.create(**params)
        else:
            delta = end_time - start_time
            for ev in rrule.rrule(dtstart=start_time, **rrule_params):
                params['start_time'] = ev
                params['end_time'] = ev + delta
                return self.occurrence_set.create(**params)

    def add_single_occurrence(self, start_time, end_time=None):
        """
        Add a single occurrence to the event, using ``start_time`` also as ``end_time`` if empty.
        """
        end_time = end_time or start_time
        params = self._make_params(start_time=start_time, end_time=start_time)
        return self.occurrence_set.create(**params)

    def upcoming_occurrences(self):
        """
        Return all occurrences that are set to start on or after the current
        time.
        """
        return self.occurrence_set.filter(start_time__gte=timezone.now())

    def next_occurrence(self):
        """
        Return the single occurrence set to start on or after the current time
        if available, otherwise ``None``.
        """
        upcoming = self.upcoming_occurrences()
        return upcoming and upcoming[0] or None

    def daily_occurrences(self, dt=None):
        """
        Convenience method wrapping ``Occurrence.objects.daily_occurrences``.
        """
        return Occurrence.objects.daily_occurrences(dt=dt, event=self)


class OccurrenceManager(MANAGER):
    use_for_related_fields = True

    def daily_occurrences(self, dt=None, event=None):
        """
        Returns a queryset of for instances that have any overlap with a
        particular day.

        * ``dt`` may be either a datetime.datetime, datetime.date object, or
          ``None``. If ``None``, default to the current day.

        * ``event`` can be an ``Event`` instance for further filtering.
        """
        dt = dt or timezone.now()
        start = datetime(dt.year, dt.month, dt.day)
        end = start.replace(hour=23, minute=59, second=59)
        qs = self.filter(
            models.Q(
                start_time__gte=start,
                start_time__lte=end,
            ) |
            models.Q(
                end_time__gte=start,
                end_time__lte=end,
            ) |
            models.Q(
                start_time__lt=start,
                end_time__gt=end
            )
        )

        return qs.filter(event=event) if event else qs


class Occurrence(BASE_CLASS):
    """
    Represents the start end time for a specific occurrence of a master ``Event``
    object.
    """
    start_time = models.DateTimeField(_('start time'), help_text=_('-'))
    end_time = models.DateTimeField(_('end time'), help_text=_('-'))
    event = models.ForeignKey(Event, verbose_name=_('event'), editable=False, help_text=_('-'))

    objects = OccurrenceManager()

    class Meta:
        verbose_name = _('occurrence')
        verbose_name_plural = _('occurrences')
        ordering = ('start_time', 'end_time')
        permissions = [
            ('view_occurrence', _('Can view occurrence')),
        ]

    def __unicode__(self):
        if self.end_time > self.start_time:
            return u'%s: %s – %s' % (self.title, self.start_time.isoformat(), self.end_time.isoformat())
        return u'%s: %s' % (self.title, self.start_time.isoformat())

    @models.permalink
    def get_absolute_url(self):
        return ('temporale-occurrence', [str(self.event.id), str(self.id)])

    def __cmp__(self, other):
        return cmp(self.start_time, other.start_time)

    @property
    def title(self):
        return self.event.title

    @property
    def description(self):
        return self.event.description

    @property
    def event_type(self):
        return self.event.event_type

    @property
    def content_type(self):
        return self.event.content_type

    @property
    def content_object(self):
        return self.event.content_object

    def wholeday(self):
        """
        Occurrence lasts the whole day?
        (time of ``start_time`` and ``end_time`` are both 00:00:00)
        """
        return (self.start_time.time() == time(0,0) == self.end_time.time())


def create_event(title, event_type, description='', start_time=None,
        end_time=None, note=None, content_object=None, **rrule_params):
    """
    Convenience function to create an ``Event``, optionally create an
    ``EventType``, and associated ``Occurrence``s. ``Occurrence`` creation
    rules match those for ``Event.add_occurrences``.

    Returns the newly created ``Event`` instance.

    Parameters

    ``event_type``
        can be either an ``EventType`` object or 2-tuple of ``(code,label)``,
        from which an ``EventType`` is either created or retrieved.

    ``start_time``
        will default to the current hour if ``None``

    ``end_time``
        will default to ``start_time`` plus temporale_settings.DEFAULT_OCCURRENCE_DURATION
        hour if ``None``

    ``note``
        some remark that you’d like to attach as a note (see `fiee-adhesive`)

    ``content_object``
        the object where you want to attach your new event

    ``freq``, ``count``, ``rrule_params``
        follow the ``dateutils`` API (see http://labix.org/python-dateutil)
    """
    from temporale import settings as temporale_settings

    model_type = ContentType.objects.get_for_model(content_object)

    if isinstance(event_type, tuple):
        new_event_type, created = EventType.objects.get_or_create(
            code=event_type[0],
            content_type=model_type,
        )
        if created:
            new_event_type.label=event_type[1]
            new_event_type.save()
    else:
        new_event_type = event_type

    event = Event.objects.create(
        title=title,
        description=description,
        event_type=new_event_type,
        content_object=content_object,
    )
    if content_object:
        # these attributes exist if the Event model inherits from a Dorsale base model
        if hasattr(event, 'createdby') and hasattr(content_object, 'createdby'):

temporale/templates/temporale/add_event.html
{% extends "temporale/base.html" %}{% load i18n %}{% csrf_token %}
{% block title %}{% trans "Add Event" %}{% endblock %}
{% block temporale_content %}
    <h2>{% trans "Add Event" %}</h2>
    {{ event_form.non_field_errors }}
    {{ recurring_form.non_field_errors }}
    {% if event_form.errors or recurrence_form.errors %}
    <p>{% trans "Please fix any errors." %}</p>
    {% endif %}
    <form method="post" action="." name="add_event">
      {% include "adhesive/notes.html" %}
        <p class="field_wrapper">
          <span class="label"><a href="../" class="button"><span class="ui-icon ui-icon-arrowthick-1-w"></span> {% trans "Back" %} </a></span>
          <span class="field">
            <a href="javascript:document.forms['add_event'].submit();" class="button"><span class="ui-icon ui-icon-disk"></span> {% trans "Save" %} </a>
          </span>
        </p>
        {% include "temporale/event_form_part.html" %}
        {% include "temporale/recurring_form_part.html" %}
    </form>

{% endblock %}

{% block rightcol %}
{% if event_form.errors or recurrence_form.errors %}
<dl class="messages">
  {% for field, errors in event_form.errors.iteritems %}
  <dt class="error">{% trans field %}</dt>
    {% for error in errors %}
    <dd class="error">{{ error }}</dd>
    {% endfor %}
  {% endfor %}
  {% for field, errors in recurrence_form.errors.iteritems %}
  <dt class="error">{% trans field %}</dt>
    {% for error in errors %}
    <dd class="error">{{ error }}</dd>
    {% endfor %}
  {% endfor %}
</dl>
{% endif %}

{% endblock %}

temporale/templates/temporale/base.html
{% extends "root.html" %}{% load i18n %}

{% if not site_profile or "temporale" in site_profile.modlist %}

{% block title %}{% trans "fiëé temporâle" %}{% endblock %}

{% block extra_head %}
{% include "adhesive/head.html" %}
{# CSS and JavaScript for date picker #}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}admin/css/widgets.css" />   
<script src="{{ STATIC_URL }}admin/js/core.js" type="text/javascript"></script> 
<script src="{{ STATIC_URL }}admin/js/calendar.js" type="text/javascript"></script> 
<script src="{{ STATIC_URL }}admin/js/admin/DateTimeShortcuts.js" type="text/javascript"></script> 
{% endblock %}

{% endif %}

{% block main_content %}
{% if not site_profile or "temporale" in site_profile.modlist %}
{% block temporale_content %}{% endblock %}
{% else %}
<p>{% trans "Sorry, you’re not cleared for the <em>temporale</em> module!" %}</p>
{% endif %}
{% endblock %}

temporale/templates/temporale/daily_view.html
{% extends "temporale/base.html" %}{% load i18n %}
{% block title %}{% trans "Daily View" %}{% endblock %}
{% block temporale_content %}
    <h2>{% trans "Daily View" %}</h2>
    <h3 class="center">
        <a href="{% url 'temporale-daily-view' prev_day.year prev_day.month prev_day.day %}" class="left" title="{% trans "Previous Day" %}">
          <span class="ui-icon ui-icon-circle-triangle-w">&lArr;</span>
        </a>
        <span>{{ day|date:"l" }}, {{ day|date:"DATE_FORMAT" }}</span>
        <a href="{% url 'temporale-daily-view' next_day.year next_day.month next_day.day %}" class="right" title="{% trans "Next Day" %}">
          <span class="ui-icon ui-icon-circle-triangle-e">&rArr;</span>
        </a>
    </h3>
    <table class="calendar itemtable">
        <thead>
            <tr>
                <th style="width:20%">{% trans "Time" %}</th>
                <th colspan="4">{% trans "Events" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for tm,cells in timeslots %}
            <tr>
                <th><a href="{% url 'temporale-add-event' %}?dtstart={{ day.date.isoformat }}T{{ tm }}">{{ tm }}</a></th>
                {% for cell in cells %}
                <td{% if cell.event_class %} class="{{cell.event_class}}"{% endif %}>{{ cell|safe }}</td>    
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

temporale/templates/temporale/event_detail.html
{% extends "temporale/base.html" %}{% load i18n %}{% csrf_token %}
{% block title %}{% blocktrans %}Event: {{ event }}{% endblocktrans %}{% endblock %}
{% block temporale_content %}
    <h2>{% trans "Event" %} {{ event }}</h2>
    <h3>{% trans "Event Details" %}</h3>
    <form action="." name="update_event" method="post">
      <input type="hidden" name="update_event" value="1" />
        {% include "adhesive/notes.html" %}

        <p class="field_wrapper">
          <span class="label"><a href="../" class="button"><span class="ui-icon ui-icon-arrowthick-1-w"></span> {% trans "Back" %} </a></span>
          <span class="field">
            <a href="javascript:document.forms['update_event'].submit();" class="button"><span class="ui-icon ui-icon-disk"></span> {% trans "Update" %} </a>
          </span>
        </p>
        {% include "temporale/event_form_part.html" %}
    </form>
    
    <h4>{% trans "Occurrences" %}</h4>
    {% if event.occurrence_set.count %}
    <ol class="occurrencelist">
        {% for o in event.occurrence_set.all %}
        <li>
            <a href="{% url 'temporale-occurrence' event.id o.id %}">
                {{ o.start_time|date:"DATETIME_FORMAT" }} &ndash; 
                {{ o.end_time|date:"DATETIME_FORMAT" }}</a>
        </li>
        {% endfor %}
    </ol>
    {% else %}
    {% endif %}
    
    <h3>{% trans "Add Occurrences" %}</h3>
    <form action="." name="add_occurrence" method="post">
      <input type="hidden" name="add_occurrence" value="1" />
        <p class="field_wrapper">
          <span class="label"><a href="../" class="button"><span class="ui-icon ui-icon-arrowthick-1-w"></span> {% trans "Back" %} </a></span>
          <span class="field">
            <a href="javascript:document.forms['add_occurrence'].submit();" class="button"><span class="ui-icon ui-icon-disk"></span> {% trans "Add" %} </a>
          </span>
        </p>
        <!-- <input type="submit" name="_add" value="{% trans "Add" %}" /> -->
        {% include "temporale/recurring_form_part.html" %}
    </form>
{% endblock %}

temporale/templates/temporale/event_form_part.html
{% load i18n %}
<p class="field_wrapper">
  <label for="id_event_type">{% trans event_form.event_type.label %}:</label>
  <span class="field_help">{% trans event_form.event_type.help_text %}</span>
  <span class="field">{{ event_form.event_type }}</span>
  {% if event_form.event_type.errors %}{% for error in event_form.event_type.errors %}
    <span class="field_errors">{{ error }} </span>
  {% endfor %}{% endif %}
</p>

<p class="field_wrapper">
  <label for="id_title">{% trans event_form.title.label %}:</label>
  <span class="field_help">{% trans event_form.title.help_text %}</span>
  <span class="field">{{ event_form.title }}</span>
  {% if event_form.title.errors %}{% for error in event_form.title.errors %}
    <span class="field_errors">{{ error }} </span>
  {% endfor %}{% endif %}
</p>

<p class="field_wrapper">
  <label for="id_description">{% trans event_form.description.label %}:</label>
  <span class="field_help">{% trans event_form.description.help_text %}</span>
  <span class="field">{{ event_form.description }}</span>
  {% if event_form.description.errors %}{% for error in event_form.description.errors %}
    <span class="field_errors">{{ error }} </span>
  {% endfor %}{% endif %}
</p>

temporale/templates/temporale/event_list.html
{% extends "temporale/base.html" %}{% load i18n %}
{% block title %}{% trans "All Events" %}{% endblock %}
{% block temporale_content %}
    <h2>{% trans "All Events" %}</h2>
    {% if events %}
    <ul class="eventlist">
        {% for e in events %}
        <li><a href="{{ e.get_absolute_url }}">{{ e }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <p>{% trans "No events found." %}</p>
    {% endif %}
{% endblock %}

temporale/templates/temporale/monthly_view.html
{% extends "temporale/base.html" %}{% load i18n %}
{% block title %}{% trans "Monthly View" %}{% endblock %}
{% block temporale_content %}
    <h2>{% trans "Monthly View" %}</h2>
    <h3 class="center">
        <a href="{% url 'temporale-monthly-view' last_month.year last_month.month %}" class="left" title="{% trans "Previous Month" %}">
          <span class="ui-icon ui-icon-circle-triangle-w">&lArr;</span>
        </a>
        <span>{{ this_month|date:"F" }} 
          <a title="{% blocktrans with this_month.year as year %}View {{ year}}{% endblocktrans %}" href="{% url 'temporale-yearly-view' this_month.year %}">
            {{ this_month|date:"Y" }}</a>
        </span>
        <a href="{% url 'temporale-monthly-view' next_month.year next_month.month %}" class="right" title="{% trans "Next Month" %}">
          <span class="ui-icon ui-icon-circle-triangle-e">&rArr;</span>
        </a>
    </h3>

    <table class="month-view itemtable">
        <thead>
            <tr>
              {% for day in week %}
                <th>{{ day }}</th>
              {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for row in calendar %}
            <tr>
                {% for day,items in row  %}
                <td{% ifequal day today.day  %} class="today"{% endifequal %}>
                {% if day %}
                    <div class="day-ordinal">
                        <a href="{% url 'temporale-daily-view' today.year today.month day %}">{{ day }}</a>
                    </div>
                    {% if items %}
                    <ul>
                        {% for item in items %}
                        <li title="{{ item.description }}">
                            {% if not item.wholeday %}<span class="event_times">{{ item.start_time|time:"H:i" }}</span>{% endif %}
                            <a href="{% if item.content_object %}{{ item.content_object.get_absolute_url }}{% else %}{{ item.get_absolute_url }}{% endif %}">
                              {{ item.title }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                {% endif %}
                </td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

temporale/templates/temporale/occurrence_detail.html
{% extends "temporale/base.html" %}{% load i18n %}{% csrf_token %}
{% block title %}{% trans "Event Occurrence" %}{% endblock %}
{% block temporale_content %}
     <h2>{% trans "Event Occurrence" %}</h2>
     <h3>
         <a href="{{ occurrence.event.get_absolute_url }}">{{ occurrence.title }}</a>
         &ndash;
         {% with occurrence.start_time as st  %}
         <a href="{% url 'temporale-daily-view' st.year st.month st.day %}">
            {{ st|date:"DATETIME_FORMAT" }}</a>
        {% endwith %}
     </h3>
     <dl class="commentlist">
         <dt>{% trans "Event type" %}:</dt>
         <dd>{{ occurrence.event.event_type }}</dd>
         
         <dt>{% trans "Description" %}:</dt>
         <dd>{{ occurrence.event.description|default:"None" }}</dd>
         
         {% with occurrence.event.notes.all as enotes %}
         {% if enotes %}
           <dt>{% trans "Notes" %}:</dt>
           {% for note in enotes %}
             <dd>{{ note }}</dd>
           {% endfor %}
         {% endif %}
         {% endwith %}
     </dl>
     
     <form action="." name="update_occurrence" method="post">
        {{ form.management_form }}
        {{ form.id }}
        {% include "adhesive/notes.html" %}
        
        {% for field in form.invisible_fields %}{{ field }}{% endfor %}
        
        {% for field in form.visible_fields %}
            <p class="field_wrapper">
              <label for="id_{{ field.name }}">{% trans field.label %}:</label>
              <span class="field">{{ field }}</span>
              {% if field.errors %}{% for error in field.errors %}
                <span class="field_errors">{{ error }} </span>
              {% endfor %}{% endif %}
            </p>
        {% endfor %}
        <p class="field_wrapper">
          <span class="label">
          <a href="../" class="button"><span class="ui-icon ui-icon-arrowthick-1-w"></span> {% trans "Back" %} </a>
          </span>
          <span class="field">
            <a href="javascript:document.forms['update_occurrence'].submit();" class="button"><span class="ui-icon ui-icon-disk"></span> {% trans "Update" %} </a>
          </span>
        </p>
     </form>

{% endblock %}

temporale/templates/temporale/root.html
{% extends "../root.html" %}

temporale/templates/temporale/yearly_view.html
{% extends "temporale/base.html" %}{% load i18n %}
{% block title %}{% blocktrans %}Year {{ year }}{% endblocktrans %}{% endblock %}
{% block temporale_content %}
    <h2>{% trans "Yearly View" %}</h2>
    <h3 class="center">
        <a href="{% url 'temporale-yearly-view' last_year %}" class="left" title="{% trans "Previous Year" %}">
          <span class="ui-icon ui-icon-circle-triangle-w">&lArr;</span>
        </a>
        <span>{{ year }}</span>
        <a href="{% url 'temporale-yearly-view' next_year %}" class="right" title="{% trans "Next Year" %}">
          <span class="ui-icon ui-icon-circle-triangle-e">&rArr;</span>
        </a>
    </h3>
    
    {% if by_month %}
    <table class="itemtable eventlist">
        <thead>
            <tr>
                <th>{% trans "Month" %}</th>
                <th>{% trans "Title" %}</th>
                <th>{% trans "Day" %}</th>
                <th>{% trans "Start" %}</th>
                <th>{% trans "End" %}</th>
            </tr>
        </thead>
        <tbody>
        {% for dt,occurrences in by_month %}
        <tr class="month-divider">
            <th rowspan="{{ occurrences|length }}">
                <a href="{% url 'temporale-monthly-view' dt.year dt.month %}">
                    {{ dt|date:"F" }}</a>
            </th>
            {% for o in occurrences %}
            <td><a href="{{ o.get_absolute_url }}">{{ o.title }}</a></td>
            <td>{{ o.start_time|date:"DATE_FORMAT" }}</td>
            <td>{{ o.start_time|date:"H:i" }}</td>
            <td>{{ o.end_time|date:"H:i" }}</td>
        </tr>
            {% if not forloop.last %}
        <tr>
            {% endif %}
            {% endfor %}
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    {% blocktrans %}<p>No events occurring in {{ year }}</p>{% endblocktrans %}
    {% endif %}
{% endblock %}